### ISSUE TITLE
Documentation warning is a bit obscure for Astroconda

### ISSUE THREAD

**Issue by hcferguson** [astroconda/astroconda#11]
`This will permanently add the repository to Conda’s search path. Be aware that adding additional anaconda.org or direct-url repositories may affect the stability of AstroConda’s run-time environment.`

For a user not familiar with anaconda, this warning is scary and not sufficiently informative. I would suggest maybe moving it to a separate section called "Caveats" or something at the end of the installation section, and being more explicit with an example of how you might inadvertently create a conflict if you do add another direct-url repository.

**Comment by jhunkeler** [comment]
I agree, this is a bit more vague than I intended. I'll see about adding a short example either inline or in the FAQ.

**Comment by jhunkeler** [comment]
https://github.com/astroconda/astroconda/pull/61

There have never been any tickets related to botched channel configurations, so it was likely safe to trim this down and forego adding a FAQ entry.
