### ISSUE TITLE
Package manifest outdated?

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda#13]
I can't tell whether this page is outdated or the new versions are simply not built yet...

http://astroconda.readthedocs.io/en/latest/package_manifest.html

**Comment by jhunkeler** [comment]
I need to implement a way for readthedocs to execute a couple scripts to populate the manifest and release notes automatically. This has been on my plate but I haven't been able to get to it. Do you have expertise with doing something like that?

https://github.com/astroconda/astroconda/blob/master/source/release_notes.py
https://github.com/astroconda/astroconda/blob/master/source/package_manifest.py

**Comment by pllim** [comment]
Well, `astropy.units` auto-generate some docstrings. It uses [generate_unit_summary()](https://github.com/astropy/astropy/blob/master/astropy/units/utils.py#L84) that appends whatever that is generated to the module docstring.

So the idea from that is to:

1. Make a dummy module (or two) in this repo.
2. Run your docstring generating functions and override the module `__doc__` with the generated docstrings (or maybe each page can be a separate dummy module?).
3. Then use `.. automodule::` to insert the generated docstring into your doc.

Will this work for you?

**Comment by jhunkeler** [comment]
fixed by #24
