### ISSUE TITLE
Activating astroconda env crashes terminal

### ISSUE THREAD

**Issue by jmccormac01** [astroconda/astroconda#14]
Hi guys,
I just followed the instructions on RTD for installing astroconda with IRAF. When I create the env the terminal window dies. 

I am running OS X El Capitan, I manage Python with Pyenv and had installed a clean version of anaconda-4.0.0 specifically just for running IRAF/PyRAF. I am also using Zsh. 

I can't dig any further as the env won't activate and I'm left with no window to try any debugging. Any ideas?

Cheers
James

**Comment by jhunkeler** [comment]
Thanks for letting me know about this. There appears to be an exit statement in the script, so instead of informing you of the error it simply ends your session.

As a temporary workaround, open the following file in an editor and remove line 37 (`exit 1`): `/path/to/anaconda/envs/[your_env]/etc/conda/activate.d/iraf.sh`

Please copy/paste the contents of that file here. `IRAFARCH` is hard-coded into `iraf.sh` during the build process so it *should* be set to `export IRAFARCH=macosx` on OS X.

**Comment by jmccormac01** [comment]
I deleted my anaconda install. I will reinstall and copy the file contents soon. Thanks.

**Comment by jmccormac01** [comment]
# Workaround for conda >4.1.2                                                                       
if [[ -n $CONDA_PREFIX ]]; then                                                                     
    export CONDA_ENV_PATH=$CONDA_PREFIX                                                             
fi                                                                                                  
export IRAFARCH=macosx                                                                              
export iraf=$CONDA_ENV_PATH/iraf/                                                                   
export MACH=$IRAFARCH                                                                               
export hostid=unix                                                                                  
export host=$iraf/$hostid/                                                                          
export hbin=$host/bin.$IRAFARCH/                                                                    
export IMTOOLRC=$iraf/dev/imtoolrc                                                                  
export tmp=/tmp/                                                                                    
                                                                                                    
export CC=gcc                                                                                       
export F2C=$hbin/f2c.e                                                                              
export F77=$hbin/f77.sh                                                                             
export RANLIB=ranlib                                                                                
                                                                                                    
case $IRAFARCH in                                                                                   
macosx)                                                                                             
export HSI_CF="-I$iraf/include -O -DMACOSX -w -Wunused -arch i386 -m32 -mmacosx-version-min=10.4"   export HSI_XF="-I$iraf/include -Inolibc -/DMACOSX -w -/Wunused -/m32 -/arch -//i386 -/mmacosx-version-min=10.4"                                                                                         export HSI_FF="-I$iraf/include -O -arch i386 -m32 -DBLD_KERNEL -mmacosx-version-min=10.4"           
export HSI_LF="-I$iraf/include -arch i386 -m32 -mmacosx-version-min=10.4"                           
;;                                                                                                  
                                                                                                    
linux)                                                                                              
export HSI_CF="-I$iraf/include -O -DLINUX -DREDHAT -DPOSIX -DSYSV -w -m32 -Wunused"                 
export HSI_FF="-I$iraf/include -O -DBLD_KERNEL -m32"                                                
export HSI_LF="-I$iraf/include -m32"                                                                
export HSI_XF="-I$iraf/include -Inolibc -w -/Wunused -/m32"                                         
;;                                                                                                  
                                                                                                    
*)                                                                                                  
echo Unknown IRAFARCH. Dying.                                                                       
;;                                                                                                                                                                                                      
esac                                                                                                
                                                                                                    
export HSI_F77LIBS=                                                                                 
export HSI_LIBS="$iraf/unix/hlib/libboot.a $iraf/lib/libsys.a $iraf/lib/libvops.a $iraf/unix/hlib/libos.a"                                                                                              export HSI_OSLIBS=                                                                                  
                                                                                                    
export UR_BITS=64                                                                                   
export UR_CPU=x86_64                                                                                
export UR_DIR=$CONDA_ENV_PATH                                                                       
export UR_VARIANT=common                                                                            
export UR_OS=osx                                                                                    
export UR_TMP=/tmp                                                                                  export UR_DIR_PKG=$UR_DIR/variants/$UR_VARIANT/

**Comment by jmccormac01** [comment]
I have edited the file as you said, then when I run ```source activate astroconda``` it still crashes out. I could not read the message so I grabbed a video of my screen and got this still right before it crashes. Any ideas?
<img width="1340" alt="screen shot 2016-07-22 at 12 54 31" src="https://cloud.githubusercontent.com/assets/1912007/17056510/9661551a-500b-11e6-93f4-8843ca0cf80c.png">

**Comment by jhunkeler** [comment]
Hmm, this failure does not match the suspected issue. 

``` bash
$ source activate astroconda
Error: activate must be sourced. Run 'source activate envname' 
instead of 'activate envname'
```

Is it possible for you to activate environments other than "astroconda"?

```bash
$ conda create -n throwaway -y python=3.5
$ source activate throwaway
# $ conda env remove -n throwaway -y
```

Have you created an alias, function, or wrapper script in your environment that replaced the built-ins: `source`, `eval` or even `activate`? The error is telling you the shell attempted to execute Conda's `activate` script directly (e.g. `$ /path/to/bin/activate` or `$ ./activate`) instead of "sourcing" it (e.g. `$ source /path/to/bin/activate` or `$ source activate`.

The following tests are compatible with `bash` and `zsh`:

- List env aliases:
``` bash
$ alias | egrep '(activate|source|eval)=.*'
```
- List env functions (by name only; remove the `grep` for full output):
``` bash
$ declare -f | grep \(\) | egrep '^activate|^source|^eval'
```
- List potential wrapper scripts

```bash
which -a activate source eval
# Note: "activate" should return the path to your miniconda installation.
```

**Comment by jmccormac01** [comment]
Hi @jhunkeler, I am using [pyenv](https://github.com/yyuu/pyenv) to wrap up all my python installations. When I run 

```which activate```

I get:

```/Users/James/.pyenv/shims/activate```

I'm not sure if there is support for Pyenv. I can try a manual installation of anaconda/astroconda if this helps. For reference, the contents of the shimmed activate are:

```
▶ more /Users/James/.pyenv/shims/activate
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/Users/James/.pyenv"
exec "/Users/James/.pyenv/libexec/pyenv" exec "$program" "$@"
```

**Comment by jmccormac01** [comment]
hi again, I've been doing some more tests using your suggestions. The throw away env also crashes too so I am wondering if it might be a pyenv issue. I've opened a ticket there as you can see above.

**Comment by jmccormac01** [comment]
Ok, so as a work around if I go to the ```astroconda env bin``` folder I can run ```source activate astroconda``` there and it will load up the environment. I think this issue is coming from pyenv. I will see if they have a solution. 

<img width="570" alt="screenshot 2016-07-25 00 36 41" src="https://cloud.githubusercontent.com/assets/1912007/17087376/563985d8-5200-11e6-8ddd-bd3bb74a716d.png">

**Comment by pllim** [comment]
Does not sound like this is actually Astroconda problem then. I propose we close this issue.
