### ISSUE TITLE
Add a link to STScI-Env doc?

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda#16]
I have found that some contents in http://stsci-env.readthedocs.io/en/latest/ are helpful even for external users, especially the ones with existing Ureka installation. Perhaps we should link the two together somehow?

c/c @saraogaz

**Comment by SaraOgaz** [comment]
Yeah, Warren brought up a similar comment, and @jhunkeler was going to chat with him about it, not sure if that happened yet...

**Comment by jhunkeler** [comment]
Sphinx supports cross-sphinx linkage, right? Couldn't we link the relevant documentation in the main AstroConda FAQ to the sections in stsci-env that are institutionally agnostic?

I don't think we should double-document things if we can help it.

**Comment by pllim** [comment]
Yes, it can be done using `intersphinx`. I use that all the time. You add the URL in as part of `intersphinx` attribute in `conf.py` and then you cross-ref in the doc like this:

```sphinx
:ref:`package:ref-to-external-doc-section`
```

or

```sphinx
:ref:`my own title <package:ref-to-external-doc-section>`
```

I have examples in `stginga` linking to Ginga like that, if you want a look-see.
