### ISSUE TITLE
Download stats?

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda#18]
Does the channel collect any download statistics? Is it even possible? Just curious.

**Comment by justincely** [comment]
I stuck google analytics on the readthedocs page a while ago, so i have read stats - but not download stats.  I think download stats are hard because so many mirror bots just clone everything all the time.

**Comment by pllim** [comment]
Yes, @jhunkeler generated some stats for me, and we also came to the same conclusion that the stats do not reflect actual usage. Hence, it is currently quite impossible to see if we can reduce or eliminate support for unused package(s). Too bad.

**Comment by pllim** [comment]
I guess I'll close this for now.
