### ISSUE TITLE
activate: No such file or directory.

### ISSUE THREAD

**Issue by richardgmcmahon** [astroconda/astroconda#19]
On Macos 10.10.5

Following http://astroconda.readthedocs.io/en/latest/installation.html

conda config --add channels http://ssb.stsci.edu/astroconda

conda create -n astroconda stsci

Extracting packages ...
[      COMPLETE      ]|###########################################################################| 100%
Linking packages ...
[      COMPLETE      ]|###########################################################################| 100%
#
# To activate this environment, use:
# $ source activate astroconda
#
# To deactivate this environment, use:
# $ source deactivate
#
143.865u 17.963s 7:15.69 37.1%	0+0k 2577+8402io 312pf+0w

rgm@dhcp-10-249-174-242(~){3}> source activate astroconda
activate: No such file or directory.

**Comment by pllim** [comment]
Are you using bash shell?

**Comment by richardgmcmahon** [comment]
I thought I was but I was using tcsh; When I start bash it worked OK, thanks
