### ISSUE TITLE
astroconda "iraf" and "IRAFARCH" environment definition 

### ISSUE THREAD

**Issue by Delosari** [astroconda/astroconda#27]
Long ago I made a few videos with the IRAF installation and how to use it:

https://www.youtube.com/watch?v=BtTr_F08y7o

However, parts of this video are quite... outdated...

I would like make a new version using the astroconda environment. I am using the latest version in ubuntu 16.04.1 (In which I have installed x11iraf using the traditional approach). I set astroconda as the default environment setting in the .bashrc this line:

export PATH="/home/user/anaconda/python2/envs/python2_iraf/bin:$PATH"

When I run the mkiraf command I get this message: 

```
-- creating a new uparm directory
Terminal types: xgterm,xterm,gterm,vt640,vt100,etc.
Enter terminal type [default xterm-256color]: xgterm
/home/vital/anaconda/python2/envs/python2_iraf/bin/mkiraf: 126: /home/vital/anaconda/python2/envs/python2_iraf/bin/mkiraf: cannot open /unix/hlib/login.cl: No such file
A new LOGIN.CL file has been created in the current directory.
You may wish to review and edit this file to change the defaults.
You may also add additional customizations to loginuser.cl
```

When I try to run the cl command I get this error
`IRAFARCH not set
`

When I try to import pyraf I get this error:

```

Your "iraf" and "IRAFARCH" environment variables are not defined and could not
be determined from /usr/local/bin/cl.  These are needed to find IRAF tasks.
Before starting pyraf, define them by doing (for example):
```

```
setenv iraf /iraf/iraf/
setenv IRAFARCH linux
```

```
at the Unix command line. Actual values will depend on your IRAF installation,
and they are set during the IRAF user installation (see iraf.net), or via
Ureka installation (see http://ssb.stsci.edu/ureka).  Also be sure to run the
"mkiraf" command to create a logion.cl (http://www.google.com/search?q=mkiraf).
```

```
/home/vital/anaconda/python2/envs/python2_iraf/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

However when I define the variables (as pyraf advices):

```
export VARIABLE=/iraf/iraf/
export IRAFARCH=linux
```

It is not working either... So which is the right way to define them without using the iraf 2.16.1 installer?

Thanks

**Comment by jpdeleon** [comment]
I have the same problem. Any updates on this?

**Comment by jhunkeler** [comment]
It is not possible simply export PATH and expect this to work. You must activate the environment correctly using conda's activation script.

Please review:
http://astroconda.readthedocs.io/en/latest/installation.html#iraf-install
