### ISSUE TITLE
iraf27 install on Unbuntu 16.04 fails

### ISSUE THREAD

**Issue by colinaspin** [astroconda/astroconda#31]
I install Anaconda2 on a new install of Ubuntu 16.04 and installed the environment iraf27.  When I run

xgterm

from bash I get this:

(iraf27) caa@obs:~$ xgterm
bash: /home/caa/anaconda2/envs/iraf27/bin/xgterm: No such file or directory

but that file does exist:

(iraf27) caa@obs:~$ ls -ltr /home/caa/anaconda2/envs/iraf27/bin/xgterm 
-rwxr-xr-x 2 caa caa 1629598 Jun 30 23:05 /home/caa/anaconda2/envs/iraf27/bin/xgterm

The same install procedure and activate procedure worked fine on Mac OSX 10.11 (using the GUI installer).

Anyone got any suggestions?

**Comment by colinaspin** [comment]
ps. get the same error from cl also.

(iraf27) caa@obs:~$ cl
/home/caa/anaconda2/envs/iraf27/bin/cl: 40: exec: /home/caa/anaconda2/envs/iraf27/iraf//bin.linux/ecl.e: not found

but the executable does exist.

(iraf27) caa@obs:~$ ls -ltr /home/caa/anaconda2/envs/iraf27/iraf/bin.linux/ecl.e
-rwxr-xr-x 2 caa caa 3935013 Feb 10  2016 /home/caa/anaconda2/envs/iraf27/iraf/bin.linux/ecl.e

**Comment by colinaspin** [comment]
OK, solved it.  Looked at a previous Ubuntu iraf problem and needed to install i386 versions of some software.  

sudo apt-get install libc6:i386 libz1:i386 libncurses5:i386 libbz2-1.0:i386 libuuid1:i386 libxcb1:i386 

then I was missing libXmy.so.6 so installed

sudo apt-get install libxmu-dev:i386 

and xgterm worked ok. As did cl.

**Comment by Protesticon** [comment]
You solved a  problem that has confused me for a month!!! If I open PyRAF without mkiraf, the packages are not available. If I mkiraf the PyRAF doesn't work at all. Yesterday I ran "cl" in an anaconda environment iraf27 and got the same error as you and then found your issue, then all was light.

**Comment by wa1kmoon** [comment]
I encountered the same problem and have solved it following you, thanks!!!
