### ISSUE TITLE
add term disambiguation

### ISSUE THREAD

**Issue by justincely** [astroconda/astroconda#43]
I've gotten multiple requests from ST people about this, so it's probably time to add it in.  We could use a high-level disambiguation of terms between anaconda, conda, astroconda

**Comment by pllim** [comment]
There are several competing charts within spacetelescope/pylunch#1

**Comment by justincely** [comment]
Thanks!  That gives me some ideas...

**Comment by jhunkeler** [comment]
Probably fixed by #48
