### ISSUE TITLE
32-bit binaries (xgterm at least) installed on my 64-bit machine

### ISSUE THREAD

**Issue by chexmix** [astroconda/astroconda#5]
Hi,

I followed the installation instructions for astroconda, activated the environment, and was confused when I tried to kick off xgterm and got this response:

`(astroconda)bash-4.3$ xgterm
bash: /home/chexmix/anaconda/envs/astroconda/bin/xgterm: No such file or directory`

... especially because the file, anyway, was definitely there. Then I thought to run the PROGRAM 'file' on xgterm itself and got this:

`(astroconda)bash-4.3$ file /home/chexmix/anaconda/envs/astroconda/bin/xgterm
/home/chexmix/anaconda/envs/astroconda/bin/xgterm: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=35f23eb005cbb739cb9e62c0e71ab8c7c2ea0b9e, not stripped`

So there's a 32-bit xgterm trying to run on my 64-bit system, and it's not working. Maybe there are other 32-bit binaries mixed in there? I don't know.

Thanks,

Glenn Becker

**Comment by jhunkeler** [comment]
Hi Glenn,

In regards to the `No such file or directory` error you're receiving... I know it sounds ridiculous, but it is related to the fact you do not have a 32-bit version of `glibc` installed on your system. ([more info](http://unix.stackexchange.com/questions/13391/getting-not-found-message-when-running-a-32-bit-binary-on-a-64-bit-system/13409#13409))
I apologize, but a rather important FAQ entry never made it into the AstroConda documentation. Here's a snippet from our previous software distribution, Ureka, which is still relevant now: 

> Many of the IRAF tasks that we include with ~~Ureka~~ AstroConda are so old that they cannot be compiled as 64-bit executables without significant changes to the source code. Because of this restriction, we always build IRAF as a 32-bit program, even for our 64-bit distributions.

> Several newer 64-bit Linux distributions no longer ship with support for 32-bit executables, which means that ~~Ureka’s~~ AstroConda's IRAF will not work on these systems without some additional packages.

If you are running Debian or Ubuntu >12.04 you can do the following to install the missing dependencies:

**If on Debian execute this first (not needed on Ubuntu):**
```
sudo dpkg --add-architecture i386
```

**Install libraries:**
```bash
sudo apt-get update
sudo apt-get install libc6:i386 libz1:i386 libncurses5:i386 libbz2-1.0:i386 libuuid1:i386 libxcb1:i386 
```

**For RHEL, CentOS, and Fedora:**

```bash
yum install glibc.i686 zlib.i686 ncurses.i686 bz2.i686 bzip2-libs.i686 uuid.i686 libxcb.i686
```

**Comment by chexmix** [comment]
Oh, okay. Nah, not ridiculous ... I just need to have a 32-bit compatibility layer present. I run Slackware, so putting that in place is slightly more complicated, but not by much. Thanks for the speedy reply! G

**Comment by jhunkeler** [comment]
No problem, Glenn.
