### ISSUE TITLE
Installation docs: missing step

### ISSUE THREAD

**Issue by keflavich** [astroconda/astroconda#56]
I was attempting to follow the instructions [here](http://astroconda.readthedocs.io/en/latest/installation.html#standard-software-stack-without-iraf) and got the following error.  Note that I got to these 'installation' instructions from [here](https://jwst-docs.stsci.edu/display/JPP/JWST+General+Target+Visibility+Tool+Help) and so I never saw the 'configure conda' page:

```
$ conda create -n astroconda stsci
Fetching package metadata ...............


PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels:
  - stsci

You can search for packages on anaconda.org with

    anaconda search -t conda stsci

```

I think this step:
```
conda config --add channels http://ssb.stsci.edu/astroconda
```
should be added somewhere on the linked page (or the "Selecting a Stack" page should link back to [configure conda](http://astroconda.readthedocs.io/en/latest/getting_started.html#configure-conda-to-use-the-astroconda-channel)).

**Comment by jhunkeler** [comment]
@keflavich Sorry for not following up here. Your suggestion was incorporated into the docs some time ago.

Thanks!
