### ISSUE TITLE
pip install into channel

### ISSUE THREAD

**Issue by MightyCristof** [astroconda/astroconda#66]
Under "Additional Software Considerations" it seems I should be able to pip something which is unavailable with conda directly into a channel: 
$ source activate astroconda
$ pip install <name_of_pkg>

When I do this it does not solely update the channel, but the root distribution. Is there anyway to pip specifically to a channel and not affect the entire distribution?

**Comment by pllim** [comment]
I think `pip` installs to wherever *it* is installed. So unless you see something like this below, your `pip` installation might be messed up.

```
$ source activate astroconda
$ which pip
~/anaconda/envs/astroconda/bin/pip
```

**Comment by rendinam** [comment]
You can install the conda `pip` package in an activated environment. That pip installation should take precedence when invoking `pip` to install non-conda packages in the selected environment.

**Comment by MightyCristof** [comment]
[cid:3E2263D9-87B4-4C80-8B97-818D2CC94B90@dartmouth.edu]

Cheers,
Chris

On Aug 1, 2017, at 11:37 AM, Matt Rendina <notifications@github.com<mailto:notifications@github.com>> wrote:


You can install the conda pip package in an activated environment. That pip installation should take precedence when invoking pip to install non-conda packages in the selected environment.

**Comment by pllim** [comment]
Please close the issue if it is answered for you. Thanks.
