### ISSUE TITLE
Feature Request: Channel name without URL

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda#68]
Currently
```
conda config --add channels http://ssb.stsci.edu/astroconda
```
but what would be really convenient and easy to remember
```
conda config --add channels astroconda
```
Why don't we have a proper channel name? Astropy has it (https://github.com/astropy/conda-channel-astropy).

**Comment by rendinam** [comment]
The name for the astroconda channel is a full URL rather than a short name like what the astropy project uses because STScI hosts the astroconda packages whereas astropy appears to publish using Continuum's infrastructure, at the expense of flexibility and a data limit for no-cost publication of packages. The longer URL, while slightly less convenient than a single word channel name buys a wealth of power in controlling how packages are provided.

**Comment by pllim** [comment]
Huh... So there's no way to add a short-form alias somehow without submitting to Continuum?

**Comment by rendinam** [comment]
That is correct. Even if there were the ability to add an alias, the user would still have to do it, and they might as well just add the URL to their channel list at that point. Short of providing our own conda installer which might pre-configure channels to avoid the need to specify a URL, or outright patch conda itself to augment its behavior, I don't see a way to get that exact functionality for STScI's channel.

**Comment by pllim** [comment]
Okay. Thanks for the clarification!

**Comment by jhunkeler** [comment]
(This is not documented anywhere by us because this method requires manual editing of ~/.condarc)

```yaml
channel_alias: http://ssb.stsci.edu

channels:
  - astroconda
  - defaults
```

So after doing that, something like this works:
```
$ conda search wcstools
Fetching package metadata ...........
wcstools                     3.9.2                         0  astroconda      
                             3.9.4                         0  astroconda      
                             3.9.4                         1  astroconda      
                             3.9.5                         0  astroconda   
```

Or more explicitly:
```
$ conda search -c astroconda wcstools
Fetching package metadata ...........
wcstools                     3.9.2                         0  astroconda      
                             3.9.4                         0  astroconda      
                             3.9.4                         1  astroconda      
                             3.9.5                         0  astroconda
```

**Comment by pllim** [comment]
@jhunkeler , `channel_alias` looks like a global alias, i.e., it will also attempt to prepend to my `astropy` channel in the config although it is not supposed to, no? I don't think this works if you have multiple custom channels defined in the config.

**Comment by jhunkeler** [comment]
@pllim Yes, you're right... conda will begin failing when you add channels that don't belong to the newly aliased URL's namespace.  Now if Continuum thought ahead a little `channels_alias` might have been a `<list>` instead of a `<str>` and allowed for multiple overrides like so:

```
channels_alias:
  - https://conda.anaconda.org/
  - http://ssb.stsci.edu/
```

Maybe some day.
