### ISSUE TITLE
Add link to PyRAF FAQ

### ISSUE THREAD

**Issue by pllim** [astroconda/astroconda#7]
Maybe it is useful to add a link to [PyRAF FAQ](http://www.stsci.edu/institute/software_hardware/pyraf/pyraf_faq) if user chooses to install PyRAF as well. There are help calls where users think it is Astroconda problem but is actually PyRAF problem.

**Comment by justincely** [comment]
From looking at the docs, I could see a link to the PyRAF FAQ being added both in the [resources](http://astroconda.readthedocs.io/en/latest/resources.html) page, but also as a bullet point in the [installations](http://astroconda.readthedocs.io/en/latest/installation.html) page either right at the top where it talks about iraf issues or near the actual iraf/pyraf install issues.  Something like: "when you have issues, first check the PyRAF FAQ..."  What do you think @jhunkeler @pllim ?

**Comment by pllim** [comment]
:+1:
