### ISSUE TITLE
An HTTP error while trying to create "astroconda" environment 

### ISSUE THREAD

**Issue by anahita25kh** [astroconda/astroconda#77]
When I try generate a new conda environment named "astroconda" as below:
 conda create -n astroconda python=2.7 iraf-all pyraf-all stsci
I get the following error. I have been trying this for a few days as I thought the parent site/ primary server may be unresponsive. 

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://astroconda.gemini.edu/public/osx-64/repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='astroconda.gemini.edu', port=80): Max retries exceeded with url: /public/osx-64/repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x10ef5a610>, 'Connection to astroconda.gemini.edu timed out. (connect timeout=9.15)'))",),)

P.S. I have done this before for many times and never had a problem.

**Comment by pllim** [comment]
This is resolved via help call. `astroconda.gemini.edu` is defunct. Please close the issue.
