### ISSUE TITLE
Need to add a notice about the discontinuation of IRAF help desk support

### ISSUE THREAD

**Issue by ivastar** [astroconda/astroconda#85]
Can we add a note that we are discontinuing help desk support for IRAF starting October 1, 2019 in BIG RED LETTERS somewhere in this section?

https://astroconda.readthedocs.io/en/latest/installation.html#legacy-software-stack-with-iraf

@pllim @rendinam @jhunkeler

**Comment by pllim** [comment]
@rendinam is on it.

**Comment by rendinam** [comment]
Big red note added.
